#!/bin/sh

USER=`whoami`

CMD=`groups ${USER} | grep dialout`

if [ "$?" -ne "0" ];then
    echo 'Error: To access USB serial devices on Linux,'
    echo 'M5Burner needs current user in group [dialout]'
    echo  'which current user ('${USER}') is not in the group'
    echo 'You should run: '
    echo ''
    echo '      sudo usermod -a -G dialout '${USER}
    echo ''
    echo '(a system reboot may be required after enroling)'
    echo ''
    exit 1
fi

newgrp dialout <<EONG
chmod a-w packages/tool/ # needed to prevent NVS tool and esptool.py from overwriting with incompatible NVS x86_64 binary 
./bin/m5burner --no-sandbox
EONG
