module.exports = {
  WIFI: 'WIFI',
  TIMERCAM_CFG: 'TIMERCAM_CFG',
  UIFLOW2_CFG: 'UIFLOW2_CFG',
  UPDATE_UIFLOW2_CFG: 'UPDATE_UIFLOW2_CFG',
  OPENAI_KEY_CFG: 'OPENAI_KEY_CFG',
  OPENAI_CAM_CFG: 'OPENAI_CAM_CFG',
  STAMPLC_CFG: 'STAMPLC_CFG'
}
